name:                pbt-sensitivity
version:             0.1.0.0
github:              "psilospore/pbt-sensitivity"
license:             BSD3
author:              "Syed Jafri"
maintainer:          "syedjafri99@gmail.com"
copyright:           "2022 Syed Jafri"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/psilospore/pbt-sensitivity#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- hmatrix

library:
  source-dirs: src

executables:
  pbt-sensitivity-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pbt-sensitivity

tests:
  pbt-sensitivity-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pbt-sensitivity
